### ISSUE TITLE
Report creation question

### ISSUE THREAD

**Issue by DorJamJr** [SplashColors/Report-Kit#3]
Hi... I'm trying to build an address book, (and a birthday list, and an anniversary list) for a family reunion. I used to use Microsoft Access to create my reports but now am strictly Mac user so Access won't work. Using Access I could build a report template and run the tool to create an address book of all entries, with formatting as I wanted. (It was, admittedly, much more powerful than I really needed.) So now I've got all my data in a csv and am looking for a tool to create custom reports. Your Report-Kit looks VERY promising for my need, but just wanted to ask if you think Report-Kit will allow me to build a formatted address book that would display all my entries. 

So "formatted" means: I can grab field 1 (Last Name) and put it at a certain location on the page, concatenate a ", ", grab field 2 (FirstName) and put it at a location to the right of field 1, grab field 3 (StreetAddress) and put that at another location on the page, etc, so maybe the "template" looks like:

LastName,     FirstName                                celPhone-1
          StreetAddress                                       celPhone-2
          City, State  PostalCode                        HomePhone
 ----------------------------------------------------------------         
          
Then the output pdf should be multiple listings in the above format (multiple listings on each page) showing all the people in my csv file.
          
So can your tool do that?

(Looks like my text is being interpreted into big bold characters... if you look at it with the "write" tab you can see what I really wanted it to look like...)

This looks like a great tool... just would like your comments prior to purchase.
Thanks so much!!  Jim

**Comment by SplashColors** [comment]
Hello Jim

Yes, you can do what you have described with Report Kit. But, keep in mind that, Report Kit, creates pdf reports from files (csv, database) but not database editor itself.

You may want to check these tutorial: https://www.youtube.com/watch?v=M3bW2UftXqc&t=2s

We are here if you have any other questions.

Thanks

**Comment by DorJamJr** [comment]
Hi! So I did purchase Report-Kit, but it looks like it really cannot do what I asked. The tool appears to only allow one line of output text for one line of CSV. What I want is to create printed output of data from more than one column, so that each record will take more than one line. Your tool lets me arrange, on one line, data from various columns ordered as I want, but still, just one line of data for each record. What I tried to describe as what I wanted to print, was something that looks like this:

Adams, Jim ................                  (303)-777-8359
...123 Main Street  ............       (720)-666-5436
...AnyCity, CO 81234

Adams, Martha..............             (970)-456-2342
...5267 Central Ave .............     (534)-998-3847
...Phoenix, AZ   88376

(etc)

So in the above example, I am using data from different columns of the same CSV line, but using them on different output lines. Sorry if I wasn't clear on my question.
Your tool lets me specify which columns are printed in which positions horizontally, but will not (as far as I can tell) allow me to use data from different fields (columns) on different output lines.

If the tool can really do what I want, can you show me how?

Thanks very much!
Jim

**Comment by SplashColors** [comment]
Hi

You mean, mix data from different sources in one line?

**Comment by DorJamJr** [comment]
Same source, different cells from one line of source, placed on different lines in output pdf. So, for example, if you have rows of source numbered 1,2,3... and columns of source labeled A,B,C... (standard Excel format), I want to generate the following output:

A1, B1      C1   D1   E1
    F1   G1      H1

A2,  B2     C2   D2   E2
    F2   G2      H2

A3,   B3     C3   D3    E3
    F3    G3    H3

(etc)

So a single line of source results (in this case) in two lines of output. In my earlier example, all the data for the address info for Jim Adams came from one line of the CSV (line 1). All the data for the address info for Martha Adams came from one line of the CSV (line 2). But the information (the name, address and phone number) wouldn't fit on a single line, so I want to spread it onto two or three lines.

Hope this is clear...

Thanks!

**Comment by SplashColors** [comment]
Ok, I think you want to use filter, filter data from the same row some similar data, you don't want that all data is pulled right?

**Comment by DorJamJr** [comment]
The basic problem is that I have a row of csv data that won’t fit on one line of a pdf and so I want to split the data from a single row of the csv so that the resulting pdf uses more than one line for each record.

(Perhaps think about how you could use your program to create address labels for envelopes… Start with a csv file that has multiple lines, with EACH line of the csv containing ALL the information required for the address. How do you create a pdf with multiple address labels, where EACH label is made up of 3 lines. That is close to what I am trying to do.)

Anyway, I did find a solution to my problem. I ended up buying a license for the Mac version of the Microsoft Office suite. The Mail Merge facility allows me to do exactly what I want. 

Best of luck with your program!

Blessings!
Jim

**Comment by SplashColors** [comment]
Ok, Thanks
